name: uncertain-ai-diagnostics
dependencies:
  - python=2.7
  - ipython
  - jupyter
  - ipykernel
  - pandas=0.20.3
  - numpy=1.12.1
  - pytest=3.2.1
  - scipy=0.19.1
  - statsmodels=0.8.0
  - click=6.7
  - seaborn=0.8
  - bokeh=0.12.7
  - matplotlib=2.0.2
  - h5py=2.7.0
  - scikit-learn=0.19
  - pip:
    - theano==0.9.0
    - https://github.com/Lasagne/Lasagne/archive/master.zip
    - keras==2.0.8
    - pathos==0.2.1
    - pillow==4.3.0
    - opencv-python
